version: 2.1
orbs:
    aws-s3: circleci/aws-s3@1.0.4
jobs:
    test:
        docker:
            - image: circleci/node
        steps:
            - restore_cache:
                  keys:
                      # when lock file changes, use increasingly general patterns to restore cache
                      - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
                      - node-v1-{{ .Branch }}-
                      - node-v1-

            - checkout
            - run: npm install
            - save_cache:
                  paths:
                      - ~/usr/local/lib/node_modules # location depends on npm version
                  key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - run: npm test
            - run: npm run lint
    deploy:
        docker:
            - image: circleci/node
        environment:
            AWS_REGION: eu-west-2
        steps:
            - restore_cache:
                  keys:
                      # when lock file changes, use increasingly general patterns to restore cache
                      - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
                      - node-v1-{{ .Branch }}-
                      - node-v1-
            - checkout
            - run: npm install
            - save_cache:
                  paths:
                      - ~/usr/local/lib/node_modules # location depends on npm version
                  key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - run: npm run build
            - aws-s3/sync:
                  from: build
                  to: "s3://hit-parade-neeko/"
                  arguments: |
                      --acl public-read \
                      --cache-control "max-age=86400" \
                  overwrite: true
workflows:
    version: 2.1
    build:
        jobs:
            - test:
              filters:
                  branches:
                      only:
                          - master
                          - develop
            - deploy:
                  requires:
                      - test
                  filters:
                      branches:
                          only: master
